## **LAB1:** QuantConnect Tutorials
>#### **Nombre:** Santiago Sánchez Mora
>#### **Asignatura:** Algoritmos
>#### **Grupo:** 1
>#### **Fecha:** 17 de Octubre de 2021











## 1. **Data Types and Data Structures**

### **1.1.** Basic Variable Types

In [161]:
# QC Code
my_string1 = 'Welcome to'
my_string2 = 'QuantConnect'
print(my_string1 + ' ' + my_string2)

Welcome to QuantConnect


In [162]:
# Changed code
my_string1 = 'Esto es'
my_string2 = 'UNcode falso'
print(my_string1 + ' ' + my_string2)

Esto es UNcode falso


---

In [163]:
# QC Code
my_int = 10
print(my_int)
print(type(my_int))

10
<class 'int'>


In [164]:
# Changed code
my_int = 4725132
print(my_int)
print(type(my_int))

4725132
<class 'int'>


---

In [165]:
# QC Code
my_string = "100"
print(type(my_string))
my_int = int(my_string)
print(type(my_int))

<class 'str'>
<class 'int'>


In [166]:
# Changed code
my_string = "4725132"
print(type(my_string))
my_int = int(my_string)
print(type(my_int))

<class 'str'>
<class 'int'>


---


In [167]:
# QC Code
my_float = 1.0
print(type(my_float))
my_int = 1
print(type(my_int))

<class 'float'>
<class 'int'>


In [168]:
# Changed code
my_float = 4725132.0
print(type(my_float))
my_int = 4725132
print(type(my_int))

<class 'float'>
<class 'int'>


---

In [169]:
# QC Code
my_string = "100"
my_float = float(my_string)
print(type(my_float))

<class 'float'>


In [170]:
# Changed code
my_string = "4725132"
my_float = float(my_string)
print(type(my_float))

<class 'float'>


---

In [171]:
# QC Code
my_bool = False
print(my_bool)
print(type(my_bool))

False
<class 'bool'>


In [172]:
# Changed code
my_bool = True
print(my_bool)
print(type(my_bool))

True
<class 'bool'>


### **1.2.** Basic Math Operations

In [173]:
# QC Code
print("Addition ", 1+1)
print("Subtraction ", 5-2)
print("Multiplication ", 2*3)
print("Division", 10/2)
print("exponent", 2**3)

Addition  2
Subtraction  3
Multiplication  6
Division 5.0
exponent 8


In [174]:
# Changed code
print("Suma ", 2+2)
print("Resta ", 9-8)
print("Multiplicación ", 6*6)
print("División", 36/6)
print("Potencia", 5**2)

Suma  4
Resta  1
Multiplicación  36
División 6.0
Potencia 25


### **1.3.** Data Collections

In [175]:
# QC Code
my_list = ['Quant', 'Connect', 1,2,3]
print(my_list)

['Quant', 'Connect', 1, 2, 3]


In [176]:
# Changed code
my_list = ['Número', 1, 'Piña', 48]
print(my_list)

['Número', 1, 'Piña', 48]


---

In [177]:
# QC Code
my_list = ['Quant', 'Connect', 1,2,3]
print(len(my_list))
print(my_list[0])
print(my_list[len(my_list) - 1])

5
Quant
3


In [178]:
# Changed code
my_list = ['Número', 1, 'Piña', 48]
print(len(my_list))
print(my_list[0])
print(my_list[len(my_list) - 1])

4
Número
48


---

In [179]:
# QC Code
my_list = ['Quant','Connect',1,2,3]
my_list[2] = 'go'
print(my_list)

['Quant', 'Connect', 'go', 2, 3]


In [180]:
# Changed code
my_list = ['Número', 1, 'Piña', 48]
my_list[0] = 'go'
print(my_list)

['go', 1, 'Piña', 48]


---

In [181]:
# QC Code
my_list = ['Quant','Connect',1,2,3]
print(my_list[1:3])

['Connect', 1]


In [182]:
# Changed code
my_list = ['Número', 1, 'Piña', 48]
print(my_list[1:3])

[1, 'Piña']


---

In [183]:
# QC Code
my_list = ['Quant','Connect',1,2,3]
print(my_list[1:])

['Connect', 1, 2, 3]


In [184]:
# Changed code
my_list = ['Número', 1, 'Piña', 48]
print(my_list[1:])

[1, 'Piña', 48]


---

In [185]:
# QC Code
my_list = ['Quant','Connect',1,2,3]
print(my_list[:3])

['Quant', 'Connect', 1]


In [186]:
# Changed code
my_list = ['Número', 1, 'Piña', 48]
print(my_list[:3])

['Número', 1, 'Piña']


---

In [187]:
# QC Code
my_list = ['Hello', 'Quant']
my_list.append('Hello')
print(my_list)
my_list.remove('Hello')
print(my_list)

['Hello', 'Quant', 'Hello']
['Quant', 'Hello']


In [188]:
# Changed code
my_list = ['Número', 1, 'Piña', 48]
my_list.append('Piña')
print(my_list)
my_list.remove('Piña')
print(my_list)

['Número', 1, 'Piña', 48, 'Piña']
['Número', 1, 48, 'Piña']


---

In [189]:
# QC Code
my_tuple = ('Welcome','to','QuantConnect')
print(my_tuple[1:]) 

('to', 'QuantConnect')


In [190]:
# Changed code
my_tuple = ('Hola','Piñata','Perro')
print(my_tuple[1:]) 

('Piñata', 'Perro')


---

In [191]:
# QC Code
stock_list = ['AAPL','GOOG','IBM','AAPL','IBM','FB','F','GOOG']
stock_set = set(stock_list)
print(stock_set)

{'GOOG', 'AAPL', 'F', 'FB', 'IBM'}


In [192]:
# Changed code
stock_list = ['Antonio','Benito','Carlos','Daniela','Elena','Fernando','Gabriela','Hernán', 'Antonio', 'Fernando']
stock_set = set(stock_list)
print(stock_set)

{'Benito', 'Fernando', 'Hernán', 'Antonio', 'Carlos', 'Daniela', 'Gabriela', 'Elena'}


---

In [193]:
# QC Code
my_dic = {'AAPL': 'Apple', 'FB': 'FaceBook', 'GOOG': 'Alphabet'}
print(my_dic['GOOG'])

Alphabet


In [194]:
# Changed code
my_dic = {'item1': 48, 'FBI': 'CSI', 'key': 'DOG'}
print(my_dic['FBI'])

CSI


---

In [195]:
# QC Code
my_dic = {'AAPL': 'Apple', 'FB': 'FaceBook', 'GOOG': 'Alphabet'}
my_dic['GOOG'] = 'Alphabet Company'
print(my_dic['GOOG'])

Alphabet Company


In [196]:
# Changed code
my_dic = {'item1': 48, 'FBI': 'CSI', 'key': 'DOG'}
my_dic['FBI'] = 'Criminal Minds'
print(my_dic['FBI'])

Criminal Minds


---

In [197]:
# QC Code
my_dic = {'AAPL': 'Apple', 'FB': 'FaceBook', 'GOOG': 'Alphabet'}
print(my_dic.keys())

dict_keys(['AAPL', 'FB', 'GOOG'])


In [198]:
# Changed code
my_dic = {'item1': 48, 'FBI': 'CSI', 'key': 'DOG'}
print(my_dic.keys())

dict_keys(['item1', 'FBI', 'key'])


### **1.4.** Common String Operations

In [199]:
# QC Code
my_str = 'Welcome to QuantConnect'
print(my_str[8:])

to QuantConnect


In [200]:
# Changed code
my_str = 'Slicing desde el caracter en la posición 7'
print(my_str[7:])

 desde el caracter en la posición 7


---

In [201]:
# QC Code
print("Counting the number of e's in this sentence".count('e'))
print('The first time e appears in this sentence'.find('e'))
print('all the a in this sentence now becomes e'.replace('a','e'))

6
2
ell the e in this sentence now becomes e


In [202]:
# Changed code
print("Este semestre es excelente".count('e'))
print('El número que resultará de aplicar este método es el 6'.find('e'))
print('Este semestre es excelente'.replace('e','3')) 

9
6
Est3 s3m3str3 3s 3xc3l3nt3


---

In [203]:
# QC Code
Time = '2016-04-01 09:43:00'
splited_list = Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date, time)
hour = time.split(':')[0]
print(hour)

2016-04-01 09:43:00
09


In [204]:
# Changed code
Time = '2077-07-07 12:13:14'
splited_list = Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date, time)
hour = time.split(':')[1]
print(hour)

2077-07-07 12:13:14
13


---

In [205]:
# QC Code
my_time = 'Hour: {}, Minute: {}'.format(9, 43)
print(my_time)

Hour: 9, Minute: 43


In [206]:
# Changed code
my_time = 'Name: {}, Age: {}, Work: {}'.format('Albertito', 18, 'Baker')
print(my_time)

Name: Albertito, Age: 18, Work: Baker


---

In [207]:
# QC Code
print('pi is %f' % 3.14)
print('%s to %s' % ('Welcome', 'QuantConnect'))

pi is 3.140000
Welcome to QuantConnect


In [208]:
# Changed code
print('euler is not %f' % 4)
print('%s to %s' % ('Welcome', 'the Jungle'))

euler is not 4.000000
Welcome to the Jungle


## 2. **Logical Operations and Loops**

### **2.1.** Logical Operations

In [209]:
# QC Code
print(1 == 0)    # 1 equals 0
print(1 == 1)    # 1 equals 1
print(1 != 0)    # 1 is not equal to 0
print(5 >= 5)    # 5 is greater than or equal to 5
print(5 >= 6)    # 5 is greater than or equal to 6

False
True
True
True
False


In [210]:
# Changed code
print(9 == 9)    # 1 equals 0
print(1 != 1)    # 1 equals 1
print(1 != 1)    # 1 is not equal to 0
print(48 >= 5)   # 5 is greater than or equal to 5
print(13 >= 34)  # 5 is greater than or equal to 6

True
False
False
True
False


---

In [211]:
# QC Code
print(2 > 1 and 3 > 2)
print(2 > 1 and 3 < 2)
print(2 > 1 or  3 < 2)
print(2 < 1 and 3 < 2)

True
False
True
False


In [212]:
# Changed code
print(3 > 4 and 3 > 2)
print(72 > 14 and 93 < 7)
print(22 > 11 or  38 < 52)
print(3 < 1 and 4 < 5)

False
False
True
False


---

In [213]:
# QC Code
print((3 > 2 or 1 < 3) and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)))
print(3 > 2 or 1 < 3 and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)))

False
True


In [214]:
# Changed code
print((1 == 1) and (2 > 0) and (4 != 9) and (0 == 0) or (7 < 2))
print(1 == 1 and 2 > 0 and 4 != 9 and (0 != 0 or 7 < 2))

True
False


### **2.2.** If Statement

In [215]:
# QC Code
i = 0
if i == 0: print('i == 0 is True')

i == 0 is True


In [216]:
# Changed code
i = 4725132
if i == 4725132: print('i == 4725135 is False')

i == 4725135 is False


---

In [217]:
# QC Code
p = 1 > 0
q = 2 > 3
if p and q:
    print('p and q is true')
elif p and not q:
    print('q is false')
elif q and not p:
    print('p is false')
else:
    print('None of p and q is true')

q is false


In [218]:
# Changed code
p = 0 == 0
q = 4725132 < 4725133
if p and q:
    print('p and q is true')
elif p and not q:
    print('q is false')
elif q and not p:
    print('p is false')
else:
    print('None of p and q is true')

p and q is true


### **2.3.** Loop Structure

In [219]:
# QC Code
i = 0
while i < 5:
    print(i)
    i += 1

0
1
2
3
4


In [220]:
# Changed code
i = 4725132
while i <= 4725140:
    print(i)
    i += 1

4725132
4725133
4725134
4725135
4725136
4725137
4725138
4725139
4725140


---

In [221]:
# QC Code
for x in [1,2,3,4,5]: print(x)

1
2
3
4
5


In [222]:
# Changed code
for x in ['Uno', 'Dos', 'Tres', 'Cuatro']: print(x)

Uno
Dos
Tres
Cuatro


---

In [223]:
# QC Code
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = []
for stock in stocks:
    if stock not in selected:
        new_list.append(stock)
print(new_list)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [224]:
# Changed code
stocks = ['Manzana', 'Piña', 'Lechuga', 'Tomate']
selected = ['Manzana','Lechuga']
new_list = []
for stock in stocks:
    if stock not in selected:
        new_list.append(stock)
print(new_list)

['Piña', 'Tomate']


---

In [225]:
# QC Code
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    print(stock)
    if stock == 'FB': break

AAPL
GOOG
IBM
FB


In [226]:
# Changed code
stocks = ['Manzana', 'Piña', 'Lechuga', 'Tomate']
for stock in stocks:
    print(stock)
    if stock == 'Piña': break

Manzana
Piña


---

In [227]:
# QC Code
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    if stock == 'FB': continue
    print(stock)

AAPL
GOOG
IBM
F
V
G
GE


In [228]:
# Changed code
stocks = ['Manzana', 'Piña', 'Lechuga', 'Tomate']
for stock in stocks:
    if stock == 'Piña': continue
    print(stock)

Manzana
Lechuga
Tomate


### **2.4.** List Comprehension

In [229]:
# QC Code
squares = []
for i in [1,2,3,4,5]:
    squares.append(i**2)
print(squares)

[1, 4, 9, 16, 25]


In [230]:
# Changed code
squares = []
for i in ['a','b','c','d','e']:
    squares.append(i*3)
print(squares)

['aaa', 'bbb', 'ccc', 'ddd', 'eee']


---

In [231]:
# QC Code
foo = [1,2,3,4,5]
squares = [x**2 for x in foo]
print(squares)

[1, 4, 9, 16, 25]


In [232]:
# Changed code
foo = ['a', 'b', 'c', 'd', 'e']
squares = [x*3 for x in foo]
print(squares)

['aaa', 'bbb', 'ccc', 'ddd', 'eee']


---

In [233]:
# QC Code
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = [x for x in stocks if x not in selected]
print(new_list)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']


In [234]:
# Changed code
stocks = ['Lápiz','Papel','Esfero','Borrador','Compás','Regla']
selected = ['Compás','Esfero']
new_list = [x for x in stocks if x not in selected]
print(new_list)

['Lápiz', 'Papel', 'Borrador', 'Regla']


---

In [235]:
# QC Code
print([(x, y) for x in [1,2,3] for y in [3,1,4] if x != y])
print([str(x) + ' vs ' + str(y) for x in ['AAPL','GOOG','IBM','FB']
                                for y in ['F','V','G','GE'] if x != y])

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]
['AAPL vs F', 'AAPL vs V', 'AAPL vs G', 'AAPL vs GE', 'GOOG vs F', 'GOOG vs V', 'GOOG vs G', 'GOOG vs GE', 'IBM vs F', 'IBM vs V', 'IBM vs G', 'IBM vs GE', 'FB vs F', 'FB vs V', 'FB vs G', 'FB vs GE']


In [236]:
# Changed code
print([(x, y) for x in ['Andrés','Santiago','Joaquin'] for y in ['Alberto','Santiago','Andrés'] if x != y])
print([str(x) + ' vs ' + str(y) for x in ['Andrés','Santiago','Joaquin']
                                for y in ['Alberto','Santiago','Andrés'] if x != y])

[('Andrés', 'Alberto'), ('Andrés', 'Santiago'), ('Santiago', 'Alberto'), ('Santiago', 'Andrés'), ('Joaquin', 'Alberto'), ('Joaquin', 'Santiago'), ('Joaquin', 'Andrés')]
['Andrés vs Alberto', 'Andrés vs Santiago', 'Santiago vs Alberto', 'Santiago vs Andrés', 'Joaquin vs Alberto', 'Joaquin vs Santiago', 'Joaquin vs Andrés']


## 3. **Functions and Objective-Oriented Programming**

### **3.1.** Functions

In [237]:
# QC Code
def product(x,y):
    return x*y
print(product(2,3))
print(product(5,10))

6
50


In [238]:
# Changed code
def product(x,y):
    return x*y
print(product('Andrea ',4))
print(product(2,30))

Andrea Andrea Andrea Andrea 
60


---

In [239]:
# QC Code
def say_hi():
    print('Welcome to QuantConnect')
say_hi()

Welcome to QuantConnect


In [240]:
# Changed code
def say_hi():
    print('Bienvenido a la Universidad Nacional de Colombia')
say_hi()

Bienvenido a la Universidad Nacional de Colombia


### **3.2.** Built-in Function

In [241]:
# QC Code
print(range(10))
print(range(1, 11))
print(range(1, 11, 2))

range(0, 10)
range(1, 11)
range(1, 11, 2)


In [242]:
# Changed code
print(range(4725132))
print(range(1, 4725132))
print(range(1, 4725132, 100))

range(0, 4725132)
range(1, 4725132)
range(1, 4725132, 100)


---

In [243]:
# QC Code
tickers = ['AAPL', 'GOOGL', 'IBM', 'FB', 'F', 'V', 'G', 'GE']
print("The number of tickers is {}".format(len(tickers)))
for k in range(len(tickers)):
    print(k + 1, tickers[k])

The number of tickers is 8
1 AAPL
2 GOOGL
3 IBM
4 FB
5 F
6 V
7 G
8 GE


In [244]:
# Changed code
tickers = ['Papel higiénico', 'Fresas', 'Durex', 'GForce RTX 3090', 'Tabaco', 'Ariel líquido', 'Oka Loka', 'Diablo Rojo']
print("Hay que comprar {} cosas para completar el mercado:".format(len(tickers)))
for k in range(len(tickers)):
    print(k + 1, tickers[k])

Hay que comprar 8 cosas para completar el mercado:
1 Papel higiénico
2 Fresas
3 Durex
4 GForce RTX 3090
5 Tabaco
6 Ariel líquido
7 Oka Loka
8 Diablo Rojo


---

In [245]:
# QC Code
tickers = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
print(list(map(len,tickers)))

[4, 4, 3, 2, 1, 1, 1, 2]


In [246]:
# Changed code
tickers = ['AAPL', (1,2), 4, {'Arroz'},'Foca', 4.56]
print(list(map(type,tickers)))

[<class 'str'>, <class 'tuple'>, <class 'int'>, <class 'set'>, <class 'str'>, <class 'float'>]


---

In [247]:
# QC Code
a = map(lambda x: x**2, range(10))
print(list(a))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [248]:
# Changed code
a = map(lambda x: x-1, range(5))
print(list(a))

[-1, 0, 1, 2, 3]


---

In [249]:
# QC Code
a = map(lambda x, y: x+y, [1,2,3,4,5], [5,4,3,2,1])
print(list(a))

[6, 6, 6, 6, 6]


In [250]:
# Changed code
a = map(lambda x, y: x+y, ['Quiero ','por ','no ','podido ','...'], ['saber ','qué ','he ','olvidarla','...'])
for x in list(a): print(x, end='')

Quiero saber por qué no he podido olvidarla......

---

In [251]:
# QC Code
sorted([5,2,3,4,1])

[1, 2, 3, 4, 5]

In [252]:
# Changed code
sorted(['a', 'b', 'h', 'd', 'g', 'c', 'e', 'f'])

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

---

In [253]:
# QC Code
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1])

[('MSFT', 69),
 ('WMT', 75.32),
 ('AAPL', 144.09),
 ('FB', 150),
 ('GOOGL', 911.71)]

In [254]:
# Changed code
price_list = [('Barriletes', 2000), ('Lasagna', 5000), ('Desodorante', 8000), ('Papel higiénico', 10000)]
sorted(price_list, key = lambda x: x[0])

[('Barriletes', 2000),
 ('Desodorante', 8000),
 ('Lasagna', 5000),
 ('Papel higiénico', 10000)]

---

In [255]:
# QC Code
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
sorted(price_list, key = lambda x: x[1], reverse = True)

[('GOOGL', 911.71),
 ('FB', 150),
 ('AAPL', 144.09),
 ('WMT', 75.32),
 ('MSFT', 69)]

In [256]:
# Changed code
price_list = [('Barriletes', 2000), ('Lasagna', 5000), ('Desodorante', 8000), ('Papel higiénico', 10000)]
sorted(price_list, key = lambda x: x[0], reverse = True)

[('Papel higiénico', 10000),
 ('Lasagna', 5000),
 ('Desodorante', 8000),
 ('Barriletes', 2000)]

---

In [257]:
# QC Code
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
price_list.sort(key = lambda x: x[1])
print(price_list)

[('MSFT', 69), ('WMT', 75.32), ('AAPL', 144.09), ('FB', 150), ('GOOGL', 911.71)]


In [258]:
# Changed code
price_list = [('Barriletes', 2000), ('Lasagna', 5000), ('Desodorante', 8000), ('Papel higiénico', 10000)]
price_list.sort(key = lambda x: x[0])
print(price_list)

[('Barriletes', 2000), ('Desodorante', 8000), ('Lasagna', 5000), ('Papel higiénico', 10000)]


### **3.3.** Object-Oriented Programming

In [259]:
# QC Code
class Stock:
    def __init__(self, ticker, open, close, volume):
        self.ticker = ticker
        self.open = open
        self.close = close
        self.volume = volume
        self.rate_return = float(close)/open - 1

    def update(self, open, close):
        self.open = open
        self.close = close
        self.rate_return = float(self.close)/self.open - 1

    def print_return(self):
        print(self.rate_return)
apple  = Stock('AAPL', 143.69, 144.09, 20109375)
google = Stock('GOOGL', 898.7, 911.7, 1561616)
print(apple.ticker)
google.print_return()
google.update(912.8,913.4)
google.print_return()

AAPL
0.014465338822744034
0.0006573181419806673


In [260]:
# Changed code
class Fruta:
    def __init__(self, Nombre, Caducidad, Cantidad, Precio):
        self.nombre = Nombre
        self.caducidad = Caducidad
        self.cantidad = Cantidad
        self.precio = Precio
        self.total_price = Cantidad * Precio

    def update(self, Cantidad, Precio):
        self.cantidad = Cantidad
        self.precio = Precio
        self.total_price = Cantidad * Precio

    def print_total_price(self):
        print(self.total_price)
fruit  = Fruta('Apple', '07/07/21', 14, 5000)
pineapple = Fruta('Pineapple', '09/07/21', 10, 8000)
print(fruit.nombre)
pineapple.print_total_price()
pineapple.update(20, 7500)
pineapple.print_total_price()

Apple
80000
150000


---

In [261]:
# QC Code
apple.ceo = 'Tim Cook'
apple.ceo

'Tim Cook'

In [262]:
# Changed code
fruit.owner = 'Pablo Palacios'
fruit.owner

'Pablo Palacios'

---

In [263]:
# QC Code
dir(apple)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'ceo',
 'close',
 'open',
 'print_return',
 'rate_return',
 'ticker',
 'update',
 'volume']

In [264]:
# Changed code
dir(fruit)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'caducidad',
 'cantidad',
 'nombre',
 'owner',
 'precio',
 'print_total_price',
 'total_price',
 'update']

---

In [265]:
class Child(Stock):
    def __init__(self, name):
        self.name = name
aa = Child('AA')
print(aa.name)
aa.update(100, 102)
print(aa.open)
print(aa.close)
aa.print_return()

AA
100
102
0.020000000000000018


In [266]:
class Frutita(Fruta):
    def __init__(self, nombre):
        self.nombre = nombre
aa = Frutita('Manzanita')
print(aa.nombre)
aa.update(15, 10000)
print(aa.cantidad)
print(aa.precio)
aa.print_total_price()

Manzanita
15
10000
150000


## 4. **NumPy and Basic Pandas**

### **4.1.** NumPy

In [267]:
# QC Code
import numpy as np

price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print(price_array, type(price_array))


[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [268]:
# Changed code
import numpy as np

price_list = [487, 565, 154, 649, 523, 978]
price_array = np.array(price_list)
print(price_array, type(price_array))


[487 565 154 649 523 978] <class 'numpy.ndarray'>


---

In [269]:
# QC Code
Ar = np.array([[1,3], [2,4]])
print(Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [270]:
# QC Code
Ar = np.array([[20,65, 84], [44,87,46]])
print(Ar, type(Ar))

[[20 65 84]
 [44 87 46]] <class 'numpy.ndarray'>


---

In [271]:
# QC Code
Ar = np.array([[1,3], [2,4]])
print(Ar.shape)

(2, 2)


In [272]:
# Changed code
Ar = np.array([[20,65, 84], [44,87,46]])
print(Ar.shape)

(2, 3)


---

In [273]:
# QC Code
Ar = np.array([[1,3], [2,4]])
print(Ar[0])
print(Ar[1])

[1 3]
[2 4]


In [274]:
# Changed code
Ar = np.array([[20,65, 84], [44,87,46]])
print(Ar[0])
print(Ar[1])

[20 65 84]
[44 87 46]


---

In [275]:
# QC Code
Ar = np.array([[1,3], [2,4]])
print('First column:', Ar[:,0])
print('Second column:', Ar[:,1])

First column: [1 2]
Second column: [3 4]


In [276]:
# Changed code
Ar = np.array([[20,65, 84], [44,87,46]])
print('First column:', Ar[:,0])
print('Second column:', Ar[:,1])

First column: [20 44]
Second column: [65 87]


---

In [277]:
# QC Code
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
np.log(price_array)

array([4.96793654, 4.98244156, 4.9675886 , 4.96995218, 4.96633504,
       4.96018375])

In [278]:
# Changed code
price_list = [487, 565, 154, 649, 523, 978]
price_array = np.array(price_list)
np.log(price_array)

array([6.18826412, 6.33682573, 5.0369526 , 6.47543272, 6.25958146,
       6.88550967])

---

In [279]:
# QC Code
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print(np.mean(price_array))
print(np.std(price_array))
print(np.sum(price_array))
print(np.max(price_array))

143.89666666666668
0.9673790478515796
863.38
145.83


In [280]:
# Changed code
price_list = [487, 565, 154, 649, 523, 978]
price_array = np.array(price_list)
print(np.mean(price_array))
print(np.std(price_array))
print(np.sum(price_array))
print(np.max(price_array))

559.3333333333334
242.96821922950244
3356
978


### **4.2.** Pandas

In [281]:
# QC Code
import pandas as pd

price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
print(s)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64


In [282]:
# QC Code
import pandas as pd

price = [487, 565, 154, 649, 523, 978]
s = pd.Series(price)
print(s)

0    487
1    565
2    154
3    649
4    523
5    978
dtype: int64


---

In [283]:
# QC Code
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price, index = ['a', 'b', 'c', 'd', 'e', 'f'])
print(s)

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64


In [284]:
# Changed code
price = [487, 565, 154, 649, 523, 978]
s = pd.Series(price, index = ['Primero', 'Segundo', 'Tercero', 'Cuarto', 'Quinto', 'Sexto'])
print(s)

Primero    487
Segundo    565
Tercero    154
Cuarto     649
Quinto     523
Sexto      978
dtype: int64


---

In [285]:
# QC Code
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price, index = ['a', 'b', 'c', 'd', 'e', 'f'])
s.index = [6,5,4,3,2,1]
print(s)

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64


In [286]:
# Changed code
price = [487, 565, 154, 649, 523, 978]
s = pd.Series(price, index = ['Primero', 'Segundo', 'Tercero', 'Cuarto', 'Quinto', 'Sexto'])
s.index = [18,17,16,15,14,13]
print(s)

18    487
17    565
16    154
15    649
14    523
13    978
dtype: int64


---

In [287]:
# QC Code
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price, index = ['a', 'b', 'c', 'd', 'e', 'f'])
s.index = [6,5,4,3,2,1]
print(s[1:])
print(s[:-2])

5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


In [288]:
# Changed code
price = [487, 565, 154, 649, 523, 978]
s = pd.Series(price, index = ['Primero', 'Segundo', 'Tercero', 'Cuarto', 'Quinto', 'Sexto'])
s.index = [18,17,16,15,14,13]
print(s[2:])
print(s[:-5])

16    154
15    649
14    523
13    978
dtype: int64
18    487
dtype: int64


---

In [289]:
# QC Code
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price, index = ['a', 'b', 'c', 'd', 'e', 'f'])
s.index = [6,5,4,3,2,1]
print(s[4])
s[4] = 0
print(s)

143.68
6    143.73
5    145.83
4      0.00
3    144.02
2    143.50
1    142.62
dtype: float64


In [290]:
# Changed code
price2 = [487, 565, 154, 649, 523, 978]
s2 = pd.Series(price2, index = ['Primero', 'Segundo', 'Tercero', 'Cuarto', 'Quinto', 'Sexto'])
s2.index = [18,17,16,15,14,13]
print(s2[18])
s2[18] = 66.87
print(s2)

487
18     66
17    565
16    154
15    649
14    523
13    978
dtype: int64


---

In [291]:
# QC Code
s = pd.Series(price, name = 'Apple Prices')
s.index = [6,5,4,3,2,1]
print(s)
print(s.name)

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Prices, dtype: float64
Apple Prices


In [292]:
# Changed code
s2 = pd.Series(price2, name = 'Números de Lotería')
s2.index= [18,17,16,15,14,13]
print(s2)
print(s2.name)

18    487
17    565
16    154
15    649
14    523
13    978
Name: Números de Lotería, dtype: int64
Números de Lotería


---

In [293]:
# QC Code
print(s.describe())

count      6.000000
mean     143.896667
std        1.059711
min      142.620000
25%      143.545000
50%      143.705000
75%      143.947500
max      145.830000
Name: Apple Prices, dtype: float64


In [294]:
# Changed code
print(s2.describe())

count      6.000000
mean     559.333333
std      266.158349
min      154.000000
25%      496.000000
50%      544.000000
75%      628.000000
max      978.000000
Name: Números de Lotería, dtype: float64


---

In [295]:
# QC Code
time_index = pd.date_range('2017-01-01', periods = len(s), freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Prices, dtype: float64


In [296]:
# Changed code
time_index2 = pd.date_range('2077-07-07', periods = len(s2), freq = 'D')
print(time_index2)
s2.index = time_index2
print(s2)

DatetimeIndex(['2077-07-07', '2077-07-08', '2077-07-09', '2077-07-10',
               '2077-07-11', '2077-07-12'],
              dtype='datetime64[ns]', freq='D')
2077-07-07    487
2077-07-08    565
2077-07-09    154
2077-07-10    649
2077-07-11    523
2077-07-12    978
Freq: D, Name: Números de Lotería, dtype: int64


---

In [297]:
# QC Code
s.index = [6,5,4,3,2,1]
print(s)
print(s[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Prices, dtype: float64
142.62


In [298]:
# Changed code
s2.index = [18,17,16,15,14,13]
print(s2)
print(s2[13])

18    487
17    565
16    154
15    649
14    523
13    978
Name: Números de Lotería, dtype: int64
978


---

In [299]:
# QC Code
print(s)
print(s.iloc[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Prices, dtype: float64
145.83


In [300]:
# Changed code
print(s2)
print(s2.iloc[1])

18    487
17    565
16    154
15    649
14    523
13    978
Name: Números de Lotería, dtype: int64
565


---

In [301]:
# QC Code
s.index = time_index
print(s['2017-01-03'])

143.68


In [302]:
# Changed code
s2.index = time_index2
print(s2['2077-07-08'])

565


---

In [303]:
# QC Code
print(s['2017-01-02':'2017-01-05'])

2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Prices, dtype: float64


In [304]:
# Changed code
print(s2['2077-07-08':'2077-07-11'])

2077-07-08    565
2077-07-09    154
2077-07-10    649
2077-07-11    523
Freq: D, Name: Números de Lotería, dtype: int64


---

In [305]:
# QC Code
print(s[s < np.mean(s)])
print(s[(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2017-01-01    143.73
2017-01-03    143.68
2017-01-05    143.50
2017-01-06    142.62
Name: Apple Prices, dtype: float64
2017-01-04    144.02
Freq: D, Name: Apple Prices, dtype: float64


In [306]:
# Changed code
print(s2[s2 < np.mean(s2)])
print(s2[(s2 > np.mean(s2)) & (s2 < np.mean(s2) + 1.64*np.std(s2))])

2077-07-07    487
2077-07-09    154
2077-07-11    523
Name: Números de Lotería, dtype: int64
2077-07-08    565
2077-07-10    649
Name: Números de Lotería, dtype: int64
